// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/custom_unitree_dog/custom_unitree_dog.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class CustomUnitreeDogImpl;

/**
 * @brief This service can be used to manage the MAVLink unitree_dog protocol.
 */
class CustomUnitreeDog : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_unitree_dog = CustomUnitreeDog(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomUnitreeDog(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_unitree_dog = CustomUnitreeDog(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomUnitreeDog(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~CustomUnitreeDog() override;


    /**
     * @brief 
     */
    enum class UnitreeDogBasicAction {
        UnitreeDogActionUnlock, /**< @brief Unlock. */
        UnitreeDogActionSitDownUp, /**< @brief Sit / Stand. */
        UnitreeDogActionRecover, /**< @brief Self-right / Recover. */
        UnitreeDogActionLightSwitch, /**< @brief Toggle lights. */
        UnitreeDogActionDance, /**< @brief Dance. */
        UnitreeDogActionJump, /**< @brief Jump. */
    };

    /**
     * @brief Stream operator to print information about a `CustomUnitreeDog::UnitreeDogBasicAction`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomUnitreeDog::UnitreeDogBasicAction const& unitree_dog_basic_action);





    /**
     * @brief Possible results returned for CustomUnitreeDog commands.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        InProgress, /**< @brief Command in progress. */
        Busy, /**< @brief public is busy and rejected command. */
        Denied, /**< @brief public denied the command. */
        Error, /**< @brief An error has occurred while executing the command. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
        NoSystem, /**< @brief No system connected. */
        ProtocolUnsupported, /**< @brief Definition file protocol not supported. */
    };

    /**
     * @brief Stream operator to print information about a `CustomUnitreeDog::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomUnitreeDog::Result const& result);



    /**
     * @brief Callback type for asynchronous CustomUnitreeDog calls.
     */
    using ResultCallback = std::function<void(Result)>;




    /**
     * @brief Prepare the custom_unitree_dog plugin (e.g. download the custom_unitree_dog definition, etc).
     *
     * This function is non-blocking. See 'prepare' for the blocking counterpart.
     */
    void prepare_async(const ResultCallback callback);



    /**
     * @brief Prepare the custom_unitree_dog plugin (e.g. download the custom_unitree_dog definition, etc).
     *
     * This function is blocking. See 'prepare_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result prepare() const;




    /**
     * @brief Basic left and right joystick control
     *
     * This function is non-blocking. See 'basic_move_control' for the blocking counterpart.
     */
    void basic_move_control_async(float lx, float ly, float rx, float ry, const ResultCallback callback);



    /**
     * @brief Basic left and right joystick control
     *
     * This function is blocking. See 'basic_move_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result basic_move_control(float lx, float ly, float rx, float ry) const;




    /**
     * @brief General key command instructions
     *
     * This function is non-blocking. See 'common_key_control' for the blocking counterpart.
     */
    void common_key_control_async(int32_t key, const ResultCallback callback);



    /**
     * @brief General key command instructions
     *
     * This function is blocking. See 'common_key_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result common_key_control(int32_t key) const;




    /**
     * @brief unlock
     *
     * This function is non-blocking. See 'unlock' for the blocking counterpart.
     */
    void unlock_async(const ResultCallback callback);



    /**
     * @brief unlock
     *
     * This function is blocking. See 'unlock_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result unlock() const;




    /**
     * @brief Squatting and standing up
     *
     * This function is non-blocking. See 'sit_stand_control' for the blocking counterpart.
     */
    void sit_stand_control_async(const ResultCallback callback);



    /**
     * @brief Squatting and standing up
     *
     * This function is blocking. See 'sit_stand_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result sit_stand_control() const;




    /**
     * @brief Basic action commands for the robot dog, e.g.: sit/stand, heart gesture, dance, etc.
     *
     * This function is non-blocking. See 'basic_action_control' for the blocking counterpart.
     */
    void basic_action_control_async(UnitreeDogBasicAction action, const ResultCallback callback);



    /**
     * @brief Basic action commands for the robot dog, e.g.: sit/stand, heart gesture, dance, etc.
     *
     * This function is blocking. See 'basic_action_control_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result basic_action_control(UnitreeDogBasicAction action) const;




    /**
     * @brief Send joystick channel commands
     *
     * This function is non-blocking.
     */
    void send_joy_stick_channel_async(float lx, float ly, float rx, float ry, const ResultCallback callback);






    /**
     * @brief Copy constructor.
     */
    CustomUnitreeDog(const CustomUnitreeDog& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const CustomUnitreeDog& operator=(const CustomUnitreeDog&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CustomUnitreeDogImpl> _impl;
};

} // namespace mavsdk