// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/custom_camera/custom_camera.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class CustomCameraImpl;

/**
 * @brief This service can be used to manage the MAVLink camera protocol.
 */
class CustomCamera : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_camera = CustomCamera(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomCamera(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_camera = CustomCamera(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomCamera(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~CustomCamera() override;


    /**
     * @brief 
     */
    enum class Status {
        Off, /**< @brief. */
        On, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::Status`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::Status const& status);

    /**
     * @brief 
     */
    enum class ImageFlip {
        HorizontalClockwise, /**< @brief. */
        HorizontalCounterClockwise, /**< @brief. */
        VerticalClockwise, /**< @brief. */
        VerticalCounterClockwise, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::ImageFlip`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::ImageFlip const& image_flip);

    /**
     * @brief 
     */
    enum class Diastimeter {
        SingleDistanceMeasurement, /**< @brief. */
        ContinuousDistanceMeasurement, /**< @brief. */
        StopMeasurement, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::Diastimeter`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::Diastimeter const& diastimeter);

    /**
     * @brief 
     */
    enum class InfraredTemperatureMode {
        InfraredtEmperaturenoNoControlMode, /**< @brief. */
        InfraredTemperatureStatus, /**< @brief. */
        InfraredTemperatureLevel, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::InfraredTemperatureMode`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::InfraredTemperatureMode const& infrared_temperature_mode);

    /**
     * @brief 
     */
    enum class InfraredTemperatureLevel {
        Level1, /**< @brief. */
        Level2, /**< @brief. */
        Level3, /**< @brief. */
        Level4, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::InfraredTemperatureLevel`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::InfraredTemperatureLevel const& infrared_temperature_level);

    /**
     * @brief 
     */
    enum class FillLightMode {
        FillLightNoControlMode, /**< @brief. */
        FillLightStatus, /**< @brief. */
        FillLightBrightness, /**< @brief. */
        FillLightSpot, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::FillLightMode`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::FillLightMode const& fill_light_mode);

    /**
     * @brief 
     */
    enum class PipMode {
        Null, /**< @brief. */
        PipMainWhiteLight, /**< @brief Main white light mode. */
        PipMainThermal, /**< @brief Main thermal imaging mode. */
        PipMainWhiteSubThermal, /**< @brief Main white light + Secondary thermal imaging mode. */
        PipMainThermalSubWhite, /**< @brief Main thermal + Secondary white light mode. */
        PipMainWideAngle, /**< @brief Main wide-angle mode. */
        PipMainWhiteSubWide, /**< @brief Main white light + Secondary wide-angle mode. */
        PipMainWideSubWhite, /**< @brief Main wide-angle + Secondary white light mode. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::PipMode`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::PipMode const& pip_mode);





    /**
     * @brief Possible results returned for Camera commands.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        InProgress, /**< @brief Command in progress. */
        Busy, /**< @brief Speaker is busy and rejected command. */
        Denied, /**< @brief Speaker denied the command. */
        Error, /**< @brief An error has occurred while executing the command. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
        NoSystem, /**< @brief No system connected. */
        ProtocolUnsupported, /**< @brief Definition file protocol not supported. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCamera::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCamera::Result const& result);



    /**
     * @brief Callback type for asynchronous CustomCamera calls.
     */
    using ResultCallback = std::function<void(Result)>;




    /**
     * @brief Prepare the custom_camera plugin (e.g. download the custom_camera definition, etc).
     *
     * This function is non-blocking. See 'prepare' for the blocking counterpart.
     */
    void prepare_async(const ResultCallback callback);



    /**
     * @brief Prepare the custom_camera plugin (e.g. download the custom_camera definition, etc).
     *
     * This function is blocking. See 'prepare_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result prepare() const;




    /**
     * @brief Picture-in-Picture Switch
     *
     * This function is non-blocking. See 'set_pip' for the blocking counterpart.
     */
    void set_pip_async(PipMode pip_mode, const ResultCallback callback);



    /**
     * @brief Picture-in-Picture Switch
     *
     * This function is blocking. See 'set_pip_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_pip(PipMode pip_mode) const;




    /**
     * @brief Pseudo Color Switch
     *
     * This function is non-blocking. See 'set_pseudo_color' for the blocking counterpart.
     */
    void set_pseudo_color_async(uint32_t pseudo_color, const ResultCallback callback);



    /**
     * @brief Pseudo Color Switch
     *
     * This function is blocking. See 'set_pseudo_color_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_pseudo_color(uint32_t pseudo_color) const;




    /**
     * @brief OSD Settings
     *
     * This function is non-blocking. See 'set_osd' for the blocking counterpart.
     */
    void set_osd_async(Status osd_status, const ResultCallback callback);



    /**
     * @brief OSD Settings
     *
     * This function is blocking. See 'set_osd_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_osd(Status osd_status) const;




    /**
     * @brief Image Flip
     *
     * This function is non-blocking. See 'set_ima_flip' for the blocking counterpart.
     */
    void set_ima_flip_async(ImageFlip image_flip, const ResultCallback callback);



    /**
     * @brief Image Flip
     *
     * This function is blocking. See 'set_ima_flip_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_ima_flip(ImageFlip image_flip) const;




    /**
     * @brief Electronic Zoom
     *
     * This function is non-blocking. See 'set_electronic_zoom' for the blocking counterpart.
     */
    void set_electronic_zoom_async(Status electronic_zoom_status, const ResultCallback callback);



    /**
     * @brief Electronic Zoom
     *
     * This function is blocking. See 'set_electronic_zoom_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_electronic_zoom(Status electronic_zoom_status) const;




    /**
     * @brief Camera Electronic Stabilization
     *
     * This function is non-blocking. See 'set_electronic_stability' for the blocking counterpart.
     */
    void set_electronic_stability_async(Status set_electronic_stability_status, const ResultCallback callback);



    /**
     * @brief Camera Electronic Stabilization
     *
     * This function is blocking. See 'set_electronic_stability_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_electronic_stability(Status set_electronic_stability_status) const;




    /**
     * @brief Infrared Temperature Camera Control
     *
     * This function is non-blocking. See 'set_infrared_temperature' for the blocking counterpart.
     */
    void set_infrared_temperature_async(Status status, InfraredTemperatureLevel level, const ResultCallback callback);



    /**
     * @brief Infrared Temperature Camera Control
     *
     * This function is blocking. See 'set_infrared_temperature_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_infrared_temperature(Status status, InfraredTemperatureLevel level) const;




    /**
     * @brief Infrared Temperature Camera Control mode
     *
     * This function is non-blocking. See 'set_infrared_temperature_control_mode' for the blocking counterpart.
     */
    void set_infrared_temperature_control_mode_async(InfraredTemperatureMode mode, const ResultCallback callback);



    /**
     * @brief Infrared Temperature Camera Control mode
     *
     * This function is blocking. See 'set_infrared_temperature_control_mode_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_infrared_temperature_control_mode(InfraredTemperatureMode mode) const;




    /**
     * @brief Laser Light
     *
     * This function is non-blocking. See 'set_laser_light' for the blocking counterpart.
     */
    void set_laser_light_async(Status status, const ResultCallback callback);



    /**
     * @brief Laser Light
     *
     * This function is blocking. See 'set_laser_light_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_laser_light(Status status) const;




    /**
     * @brief Laser Range Finder
     *
     * This function is non-blocking. See 'set_laser_range_finder' for the blocking counterpart.
     */
    void set_laser_range_finder_async(Diastimeter laser_range_status, const ResultCallback callback);



    /**
     * @brief Laser Range Finder
     *
     * This function is blocking. See 'set_laser_range_finder_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_laser_range_finder(Diastimeter laser_range_status) const;




    /**
     * @brief Human and Vehicle Detection
     *
     * This function is non-blocking. See 'set_human_vehicle_detection' for the blocking counterpart.
     */
    void set_human_vehicle_detection_async(Status human_vehicle_detection_status, const ResultCallback callback);



    /**
     * @brief Human and Vehicle Detection
     *
     * This function is blocking. See 'set_human_vehicle_detection_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_human_vehicle_detection(Status human_vehicle_detection_status) const;




    /**
     * @brief Fill Light Control
     *
     * This function is non-blocking. See 'set_fill_light' for the blocking counterpart.
     */
    void set_fill_light_async(Status status, uint32_t brightness, uint32_t light_spot, const ResultCallback callback);



    /**
     * @brief Fill Light Control
     *
     * This function is blocking. See 'set_fill_light_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_fill_light(Status status, uint32_t brightness, uint32_t light_spot) const;




    /**
     * @brief set Fill Light Control mode
     *
     * This function is non-blocking. See 'set_fill_light_mode' for the blocking counterpart.
     */
    void set_fill_light_mode_async(FillLightMode flag, const ResultCallback callback);



    /**
     * @brief set Fill Light Control mode
     *
     * This function is blocking. See 'set_fill_light_mode_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_fill_light_mode(FillLightMode flag) const;




    /**
     * @brief camera param save
     *
     * This function is non-blocking. See 'set_camera_param_save' for the blocking counterpart.
     */
    void set_camera_param_save_async(const ResultCallback callback);



    /**
     * @brief camera param save
     *
     * This function is blocking. See 'set_camera_param_save_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_camera_param_save() const;




    /**
     * @brief Switch camera lens
     *
     * This function is non-blocking. See 'switch_camera_lens' for the blocking counterpart.
     */
    void switch_camera_lens_async(uint32_t lens_index, const ResultCallback callback);



    /**
     * @brief Switch camera lens
     *
     * This function is blocking. See 'switch_camera_lens_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result switch_camera_lens(uint32_t lens_index) const;






    /**
     * @brief Select current camera .
     *
     * Bind the plugin instance to a specific camera_id
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    Result select_camera(int32_t camera_id) const;


    /**
     * @brief Copy constructor.
     */
    CustomCamera(const CustomCamera& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const CustomCamera& operator=(const CustomCamera&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CustomCameraImpl> _impl;
};

} // namespace mavsdk