// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/custom_plane/custom_plane.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class CustomPlaneImpl;

/**
 * @brief This service can be used to manage the MAVLink plane protocol.
 */
class CustomPlane : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_plane = CustomPlane(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomPlane(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_plane = CustomPlane(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit CustomPlane(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~CustomPlane() override;


    /**
     * @brief 
     */
    enum class DataCollectionStatus {
        DataCollectionOn, /**< @brief. */
        DataCollectionOff, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomPlane::DataCollectionStatus`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomPlane::DataCollectionStatus const& data_collection_status);

    /**
     * @brief 
     */
    enum class ClutchStatus {
        On, /**< @brief. */
        Off, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomPlane::ClutchStatus`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomPlane::ClutchStatus const& clutch_status);

    /**
     * @brief 
     */
    enum class CollectionFrequency {
        Frequency50, /**< @brief. */
        Frequency100, /**< @brief. */
        Frequency200, /**< @brief. */
        Frequency500, /**< @brief. */
        Frequency1000, /**< @brief. */
    };

    /**
     * @brief Stream operator to print information about a `CustomPlane::CollectionFrequency`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomPlane::CollectionFrequency const& collection_frequency);




    /**
     * @brief 
     */
    struct StrainGaugeData {
        
        std::string data{}; /**< @brief Actual data content, fixed to 210 bytes */
    };

    /**
     * @brief Equal operator to compare two `CustomPlane::StrainGaugeData` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const CustomPlane::StrainGaugeData& lhs, const CustomPlane::StrainGaugeData& rhs);

    /**
     * @brief Stream operator to print information about a `CustomPlane::StrainGaugeData`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomPlane::StrainGaugeData const& strain_gauge_data);





    /**
     * @brief Possible results returned for plane commands.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        InProgress, /**< @brief Command in progress. */
        Busy, /**< @brief plane is busy and rejected command. */
        Denied, /**< @brief plane denied the command. */
        Error, /**< @brief An error has occurred while executing the command. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
        NoSystem, /**< @brief No system connected. */
        ProtocolUnsupported, /**< @brief Definition file protocol not supported. */
    };

    /**
     * @brief Stream operator to print information about a `CustomPlane::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomPlane::Result const& result);



    /**
     * @brief Callback type for asynchronous CustomPlane calls.
     */
    using ResultCallback = std::function<void(Result)>;




    /**
     * @brief Prepare the custom_plane plugin (e.g. download the custom_plane definition, etc).
     *
     * This function is non-blocking. See 'prepare' for the blocking counterpart.
     */
    void prepare_async(const ResultCallback callback);



    /**
     * @brief Prepare the custom_plane plugin (e.g. download the custom_plane definition, etc).
     *
     * This function is blocking. See 'prepare_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result prepare() const;




    /**
     * @brief Control strain gauge data collection
     *
     * This function is non-blocking. See 'control_data_collection' for the blocking counterpart.
     */
    void control_data_collection_async(DataCollectionStatus status, uint32_t hour, uint32_t minute, uint32_t second, const ResultCallback callback);



    /**
     * @brief Control strain gauge data collection
     *
     * This function is blocking. See 'control_data_collection_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result control_data_collection(DataCollectionStatus status, uint32_t hour, uint32_t minute, uint32_t second) const;




    /**
     * @brief Control servo
     *
     * This function is non-blocking. See 'control_servo' for the blocking counterpart.
     */
    void control_servo_async(uint32_t servo_num, float position, const ResultCallback callback);



    /**
     * @brief Control servo
     *
     * This function is blocking. See 'control_servo_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result control_servo(uint32_t servo_num, float position) const;




    /**
     * @brief Control clutch
     *
     * This function is non-blocking. See 'control_clutch' for the blocking counterpart.
     */
    void control_clutch_async(ClutchStatus status, uint32_t num, const ResultCallback callback);



    /**
     * @brief Control clutch
     *
     * This function is blocking. See 'control_clutch_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result control_clutch(ClutchStatus status, uint32_t num) const;




        

    /**
     * @brief Callback type for subscribe_strain_gauge_data.
     */
    using StrainGaugeDataCallback = std::function<void(StrainGaugeData)>;

    /**
     * @brief Handle type for subscribe_strain_gauge_data.
     */
    using StrainGaugeDataHandle = Handle<StrainGaugeData>;

    /**
     * @brief Subscribe to strain gauge data
     */
    StrainGaugeDataHandle subscribe_strain_gauge_data(const StrainGaugeDataCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_strain_gauge_data
     */
    void unsubscribe_strain_gauge_data(StrainGaugeDataHandle handle);

        



    /**
     * @brief Poll for 'StrainGaugeData' (blocking).
     *
     * @return One StrainGaugeData update.
     */
    StrainGaugeData strain_gauge_data() const;




    /**
     * @brief Calibration of strain gauge
     *
     * This function is non-blocking. See 'gauge_calibration' for the blocking counterpart.
     */
    void gauge_calibration_async(uint32_t value, const ResultCallback callback);



    /**
     * @brief Calibration of strain gauge
     *
     * This function is blocking. See 'gauge_calibration_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result gauge_calibration(uint32_t value) const;




    /**
     * @brief Parameter saving
     *
     * This function is non-blocking. See 'parameter_save' for the blocking counterpart.
     */
    void parameter_save_async(const ResultCallback callback);



    /**
     * @brief Parameter saving
     *
     * This function is blocking. See 'parameter_save_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result parameter_save() const;




    /**
     * @brief Parameter saving
     *
     * This function is non-blocking. See 'set_collection_frequency' for the blocking counterpart.
     */
    void set_collection_frequency_async(CollectionFrequency hz, const ResultCallback callback);



    /**
     * @brief Parameter saving
     *
     * This function is blocking. See 'set_collection_frequency_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result set_collection_frequency(CollectionFrequency hz) const;




    /**
     * @brief Copy constructor.
     */
    CustomPlane(const CustomPlane& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const CustomPlane& operator=(const CustomPlane&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CustomPlaneImpl> _impl;
};

} // namespace mavsdk