// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/skylink/skylink.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "plugin_base.h"

#include "handle.h"

namespace mavsdk {


class System;class SkylinkImpl;

/**
 * @brief Can be used to manage skylinks that implement the MAVLink
 * Skylink Protocol: .
 *
 * Currently only a single skylink is supported.
 * When multiple skylinks are supported the plugin will need to be
 * instantiated separately for every skylink
 */
class Skylink : public PluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto skylink = Skylink(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Skylink(System& system); // deprecated

    /**
     * @brief Constructor. Creates the plugin for a specific System.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto skylink = Skylink(system);
     *     ```
     *
     * @param system The specific system associated with this plugin.
     */
    explicit Skylink(std::shared_ptr<System> system); // new


    /**
     * @brief Destructor (internal use only).
     */
    ~Skylink() override;


    /**
     * @brief File update type.
     */
    enum class FileUpdateType {
        None, /**< @brief Unknown file update type. */
        Add, /**< @brief File added. */
        Remove, /**< @brief File deleted. */
        Rename, /**< @brief File renamed. */
        Modify, /**< @brief File modified. */
    };

    /**
     * @brief Stream operator to print information about a `Skylink::FileUpdateType`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::FileUpdateType const& file_update_type);





    /**
     * @brief Possible results returned for skylink commands
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        InProgress, /**< @brief Command in progress. */
        Busy, /**< @brief Skylink is busy and rejected command. */
        Denied, /**< @brief Skylink denied the command. */
        Error, /**< @brief An error has occurred while executing the command. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
        NoSystem, /**< @brief No system connected. */
        ProtocolUnsupported, /**< @brief Definition file protocol not supported. */
    };

    /**
     * @brief Stream operator to print information about a `Skylink::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::Result const& result);





    /**
     * @brief Type to represent a skylink information.
     */
    struct Information {
        
        std::string vendor_name{}; /**< @brief Name of the skylink vendor */
        std::string model_name{}; /**< @brief Name of the skylink model */
        std::string serial_number{}; /**< @brief Serial number of the skylink */
        std::string firmware_version{}; /**< @brief Firmware version of the skylink */
    };

    /**
     * @brief Equal operator to compare two `Skylink::Information` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Skylink::Information& lhs, const Skylink::Information& rhs);

    /**
     * @brief Stream operator to print information about a `Skylink::Information`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::Information const& information);






    /**
     * @brief Information about the skylink storage.
     */
    struct StorageInformation {
        
        /**
     * @brief Storage status type.
     */
    enum class StorageStatus {
        NotAvailable, /**< @brief Storage not available. */
        Unformatted, /**< @brief Storage is not formatted (i.e. has no recognized file system). */
        Formatted, /**< @brief Storage is formatted (i.e. has recognized a file system). */
        NotSupported, /**< @brief Storage status is not supported. */
    };

    /**
     * @brief Stream operator to print information about a `Skylink::StorageStatus`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::StorageInformation::StorageStatus const& storage_status);
        
        /**
     * @brief Storage type.
     */
    enum class StorageType {
        Unknown, /**< @brief Storage type unknown. */
        UsbStick, /**< @brief Storage type USB stick. */
        Sd, /**< @brief Storage type SD card. */
        Microsd, /**< @brief Storage type MicroSD card. */
        Hd, /**< @brief Storage type HD mass storage. */
        Other, /**< @brief Storage type other, not listed. */
    };

    /**
     * @brief Stream operator to print information about a `Skylink::StorageType`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::StorageInformation::StorageType const& storage_type);
        
        StorageStatus storage_status{}; /**< @brief Storage status */
        StorageType storage_type{}; /**< @brief Storage type */
        float total_storage_mib{}; /**< @brief Total storage (in MiB) */
        float used_storage_mib{}; /**< @brief Used storage (in MiB) */
        float available_storage_mib{}; /**< @brief Available storage (in MiB) */
    };

    /**
     * @brief Equal operator to compare two `Skylink::StorageInformation` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Skylink::StorageInformation& lhs, const Skylink::StorageInformation& rhs);

    /**
     * @brief Stream operator to print information about a `Skylink::StorageInformation`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::StorageInformation const& storage_information);




    /**
     * @brief Information about a .
     */
    struct FileInfo {
        
        std::string name{}; /**< @brief The name of file */
        uint32_t index{}; /**< @brief The index of file */
    };

    /**
     * @brief Equal operator to compare two `Skylink::FileInfo` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Skylink::FileInfo& lhs, const Skylink::FileInfo& rhs);

    /**
     * @brief Stream operator to print information about a `Skylink::FileInfo`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::FileInfo const& file_info);




    /**
     * @brief 
     */
    struct NotifyFileOperation {
        
        FileUpdateType update_type{}; /**< @brief file update type */
        uint32_t index{}; /**< @brief index of the file */
    };

    /**
     * @brief Equal operator to compare two `Skylink::NotifyFileOperation` objects.
     *
     * @return `true` if items are equal.
     */
    friend bool operator==(const Skylink::NotifyFileOperation& lhs, const Skylink::NotifyFileOperation& rhs);

    /**
     * @brief Stream operator to print information about a `Skylink::NotifyFileOperation`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, Skylink::NotifyFileOperation const& notify_file_operation);


    /**
     * @brief Callback type for asynchronous Skylink calls.
     */
    using ResultCallback = std::function<void(Result)>;




    /**
     * @brief Prepare the skylink plugin (e.g. download the skylink definition, etc).
     *
     * This function is non-blocking. See 'prepare' for the blocking counterpart.
     */
    void prepare_async(const ResultCallback callback);



    /**
     * @brief Prepare the skylink plugin (e.g. download the skylink definition, etc).
     *
     * This function is blocking. See 'prepare_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result prepare() const;




        

    /**
     * @brief Callback type for subscribe_information.
     */
    using InformationCallback = std::function<void(Information)>;

    /**
     * @brief Handle type for subscribe_information.
     */
    using InformationHandle = Handle<Information>;

    /**
     * @brief Subscribe to skylink information updates.
     */
    InformationHandle subscribe_information(const InformationCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_information
     */
    void unsubscribe_information(InformationHandle handle);

        



    /**
     * @brief Poll for 'Information' (blocking).
     *
     * @return One Information update.
     */
    Information information() const;




        

    /**
     * @brief Callback type for subscribe_storage_information.
     */
    using StorageInformationCallback = std::function<void(StorageInformation)>;

    /**
     * @brief Handle type for subscribe_storage_information.
     */
    using StorageInformationHandle = Handle<StorageInformation>;

    /**
     * @brief Subscribe to skylink status updates.
     */
    StorageInformationHandle subscribe_storage_information(const StorageInformationCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_storage_information
     */
    void unsubscribe_storage_information(StorageInformationHandle handle);

        



    /**
     * @brief Poll for 'StorageInformation' (blocking).
     *
     * @return One StorageInformation update.
     */
    StorageInformation storage_information() const;




        

    /**
     * @brief Callback type for subscribe_file_info.
     */
    using FileInfoCallback = std::function<void(FileInfo)>;

    /**
     * @brief Handle type for subscribe_file_info.
     */
    using FileInfoHandle = Handle<FileInfo>;

    /**
     * @brief Subscribe to  file information.
     */
    FileInfoHandle subscribe_file_info(std::string file_name, const FileInfoCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_file_info
     */
    void unsubscribe_file_info(FileInfoHandle handle);

        



    /**
     * @brief Poll for 'FileInfo' (blocking).
     *
     * @return One FileInfo update.
     */
    FileInfo file_info(std::string file_name) const;




    /**
     * @brief Notify files updated.
     *
     * This function is non-blocking. See 'notify_file_update' for the blocking counterpart.
     */
    void notify_file_update_async(NotifyFileOperation file_operation, const ResultCallback callback);



    /**
     * @brief Notify files updated.
     *
     * This function is blocking. See 'notify_file_update_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result notify_file_update(NotifyFileOperation file_operation) const;




    /**
     * @brief Update the firmware of the skylink.
     *
     * This function is non-blocking. See 'update_firmware' for the blocking counterpart.
     */
    void update_firmware_async(const ResultCallback callback);



    /**
     * @brief Update the firmware of the skylink.
     *
     * This function is blocking. See 'update_firmware_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result update_firmware() const;




    /**
     * @brief Restart the skylink plugin.
     *
     * This function is non-blocking. See 'restart' for the blocking counterpart.
     */
    void restart_async(const ResultCallback callback);



    /**
     * @brief Restart the skylink plugin.
     *
     * This function is blocking. See 'restart_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result restart() const;




    /**
     * @brief Enter developer mode
     *
     * This function is non-blocking. See 'enter_dev_mode' for the blocking counterpart.
     */
    void enter_dev_mode_async(std::string pwd, const ResultCallback callback);



    /**
     * @brief Enter developer mode
     *
     * This function is blocking. See 'enter_dev_mode_async' for the non-blocking counterpart.
     *
     * @return Result of request.
     */
    Result enter_dev_mode(std::string pwd) const;




    /**
     * @brief Copy constructor.
     */
    Skylink(const Skylink& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const Skylink& operator=(const Skylink&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<SkylinkImpl> _impl;
};

} // namespace mavsdk