// WARNING: THIS FILE IS AUTOGENERATED! As such, it should not be edited.
// Edits need to be made to the proto files
// (see https://github.com/mavlink/MAVSDK-Proto/blob/main/protos/custom_camera_server/custom_camera_server.proto)

#pragma once

#include <array>
#include <cmath>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <utility>
#include <vector>


#include "server_plugin_base.h"

#include "handle.h"

namespace mavsdk {


class ServerComponent;
class CustomCameraServerImpl;

/**
 * @brief This service can be used to manage the MAVLink camera server protocol.
 */
class CustomCameraServer : public ServerPluginBase {
public:

    /**
     * @brief Constructor. Creates the plugin for a ServerComponent instance.
     *
     * The plugin is typically created as shown below:
     *
     *     ```cpp
     *     auto custom_camera_server = CustomCameraServer(server_component);
     *     ```
     *
     * @param server_component The ServerComponent instance associated with this server plugin.
     */
    explicit CustomCameraServer(std::shared_ptr<ServerComponent> server_component);


    /**
     * @brief Destructor (internal use only).
     */
    ~CustomCameraServer() override;


    /**
     * @brief Possible feedback results for custom_camera respond command.
     */
    enum class CameraFeedback {
        Unknown, /**< @brief Unknown. */
        Ok, /**< @brief Ok. */
        Busy, /**< @brief Busy. */
        Failed, /**< @brief Failed. */
        Inprogress, /**< @brief In progress. */
        Denied, /**< @brief Denied. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCameraServer::CameraFeedback`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCameraServer::CameraFeedback const& camera_feedback);





    /**
     * @brief Possible results returned for Camera commands.
     */
    enum class Result {
        Unknown, /**< @brief Unknown result. */
        Success, /**< @brief Command executed successfully. */
        InProgress, /**< @brief Command in progress. */
        Busy, /**< @brief Custom_Camera is busy and rejected command. */
        Denied, /**< @brief Custom_Camera denied the command. */
        Error, /**< @brief An error has occurred while executing the command. */
        Timeout, /**< @brief Command timed out. */
        WrongArgument, /**< @brief Command has wrong argument(s). */
        NoSystem, /**< @brief No system connected. */
        ProtocolUnsupported, /**< @brief Definition file protocol not supported. */
    };

    /**
     * @brief Stream operator to print information about a `CustomCameraServer::Result`.
     *
     * @return A reference to the stream.
     */
    friend std::ostream& operator<<(std::ostream& str, CustomCameraServer::Result const& result);



    /**
     * @brief Callback type for asynchronous CustomCameraServer calls.
     */
    using ResultCallback = std::function<void(Result)>;




        

    /**
     * @brief Callback type for subscribe_switch_camera_lens.
     */
    using SwitchCameraLensCallback = std::function<void(uint32_t)>;

    /**
     * @brief Handle type for subscribe_switch_camera_lens.
     */
    using SwitchCameraLensHandle = Handle<uint32_t>;

    /**
     * @brief Subscribe to switch camera lens requests. Each request received should respond to using RespondSwitchCameraLens.
     */
    SwitchCameraLensHandle subscribe_switch_camera_lens(const SwitchCameraLensCallback& callback);

    /**
     * @brief Unsubscribe from subscribe_switch_camera_lens
     */
    void unsubscribe_switch_camera_lens(SwitchCameraLensHandle handle);

        








    /**
     * @brief Respond to a switch camera lens request from SubscribeSwitchCameraLens.
     *
     * This function is blocking.
     *
     * @return Result of request.
     */
    Result respond_switch_camera_lens(CameraFeedback camera_feedback) const;




    /**
     * @brief Copy constructor.
     */
    CustomCameraServer(const CustomCameraServer& other);

    /**
     * @brief Equality operator (object is not copyable).
     */
    const CustomCameraServer& operator=(const CustomCameraServer&) = delete;

private:
    /** @private Underlying implementation, set at instantiation */
    std::unique_ptr<CustomCameraServerImpl> _impl;
};

} // namespace mavsdk